In [46]:
import pandas as pd
import numpy as np

In [12]:
def import_data():
    data = pd.read_csv('./norway_new_car_sales_by_make.csv')
    data['Period'] = data['Year'].astype(str) + '-' + data['Month'].astype(str).str.zfill(2)
    df = pd.pivot_table(data=data, values='Quantity', index='Make', columns='Period', aggfunc='sum', fill_value=0)
    return df

df = import_data()


In [96]:
def datasets(df, x_len=6, y_len=1, test_loop=3):
    D = df.values
    rows, periods = D.shape
    
    # Training set creation
    loops = periods + 1 - x_len - y_len
    train = []
    for col in range(loops):
        train.append(D[:,col:col+x_len+y_len])
    train = np.vstack(train)
    X_train, Y_train = np.split(train, [-y_len],axis=1 )
    
    # Test set creation
    if test_loop > 0:
        X_train, X_test = np.split(X_train, [-rows*test_loop], axis=0)
        Y_train, Y_test = np.split(Y_train, [-rows*test_loop], axis=0)
    else:
        X_test = D[:, -x_len:]
        Y_test = np.full((X_test.shape[0],y_len), np.nan)
        
        
    
    print(X_train, "\n----\n",Y_train, "\n----\n",X_test, "\n----\n",Y_test)
    return 

datasets(df.iloc[0:1,0:12])
    

[[16  9 21 20 17 21]
 [ 9 21 20 17 21 14]
 [21 20 17 21 14 12]] 
----
 [[14]
 [12]
 [15]] 
----
 [[20 17 21 14 12 15]
 [17 21 14 12 15 10]
 [21 14 12 15 10 18]] 
----
 [[10]
 [18]
 [21]]


In [92]:
df.iloc[0:1,0:12]

Period      2007-01  2007-02  2007-03  2007-04  2007-05  2007-06  2007-07  \
Make                                                                        
Alfa Romeo       16        9       21       20       17       21       14   

Period      2007-08  2007-09  2007-10  2007-11  2007-12  
Make                                                     
Alfa Romeo       12       15       10       18       21